server:
  port: 3000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:sensediadb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#    encoding: UTF-8
#    schemas: public
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      base-path: /v1/actuator
      exposure:
        include: actuator,logfile,metrics,health,info
